# Path to the data files *.CSV
Data_filename_hour: data/OANDA:EURUSD_hour.CSV
Data_filename_minute: data/OANDA:EURUSD_minute.CSV

# Timeframe for backtesting 'year-month-day'
Backtesting_dates:
  start: '2025-01-01'
  end: '2025-12-01'

# size type: 'value' 'amount' 'percent'
Trade:
  size: 0.3
  size_type: percent

# Fees for one amount of trade in percent
# Fixed fees for one trade in currency units
Broker:
  fees: 0
  fixed_fees: 0

# Slippage in percent
Slippage: 0

# Start cash value
Initial_cash: 50000

# Risk to Reward ratio
RR: 1

# Stop Loss in percent. Depends on the RR. 1 is 100% of RR
# If you dont need optimization use only 'start'
SL:
  start: 0.1
  end: 0.5
  step: 0.1

# Take Profit in percent. Depends on the RR. 1 is 100% of RR
# If you dont need optimization use only 'start'
TP:
  start: 1
  end: 1.5
  step: 0.1

# Timeframe to open trades 'hour:minute'
# Only for backtesting on minute candles
Trading_time:
  Start_time: '00:00'
  End_time: '23:59'