# Path to the data files *.CSV
Data_filename_hour: data/OANDA:EURUSD_hour.CSV
Data_filename_minute: data/OANDA:EURUSD_minute.CSV

# size type: 'value' 'amount' 'percent'
Trade:
  size: 0.3
  size_type: percent

# Fees for one amount of trade in percent
# Fixed fees for one trade in currency units
Broker:
  fees: 0
  fixed_fees: 0

# Slippage in percent
Slippage: 0

# Start cash value
Initial_cash: 50000

# Risk to Reward ratio
RR: 1

# Stop Loss in percent. Depends on the RR. 1 is 100% of RR
SL: 0.5

# Take Profit in percent. Depends on the RR. 1 is 100% of RR
TP: 1