# Time interval of data
Time interval:
  Start_year: 2024
  Start_month: 1
  End_year: 2025
  End_month: 12        

# Place from which take data
# Name of token which data you need
Data info:
  Exchange: OANDA
  Token: EURUSD

# Time frequency of the data 'minute', 'hour'
Frequency: minute